Add helm chart
nabsul/k8s-ecr-login-renew pull request #28
Opened 2022-01-13 06:14 UTC by devec0

Hello,

Thank you for writing k8s-ecr-login-renew, and sharing it! It definitely saved me some heartache today.

Noticing #23 - and having decent experience with writing helm charts - and needing to deploy this via Helm myself, I thought I'd write and contribute a chart to this project. As noted in #23 - people who are maintaining complex Kubernetes deployments are quite commonly using Helm due to the templating and secret-handling utility is has, as well as companion tools such as `helmfile` to help keep multi-environment deployments as DRY as possible. This was my use case, so I hope this chart will help others.

I've tested this chart myself and it is working well.

I've tried to keep it as minimal and secure as possible following the good example in the `examples` folder. I have not added the ability to specify multiple repositories to the chart, but that would be quite easy to add later if someone needed it in a non-breaking way.

Let me know if any questions or if you have any changes you'd like to see.

2022-01-16 18:09 UTC, nabsul commented
Thanks for the contribution @devec0 ! As someone who doesn't use it at all, I'm hoping looking forward to using your PR to learn more about Helm. 

I'll try to review this ASAP, but please be patient. If you don't hear back from me in a couple of weeks, please feel free to ping me with a reminder.

Thanks again!

2022-04-07 12:26 UTC, xavidop commented
thanks for this contribution @devec0 ! this is so much needed!

2022-04-07 12:41 UTC, xavidop requested changes

2022-04-07 12:41 UTC, xavidop commented on chart/templates/cron.yaml
> +                    key: DOCKER_SECRET_NAME
here you have missed:
```
              - name: TARGET_NAMESPACE
                value: {{ .Release.Namespace }}
```
if not it will apply on the default namespace

2022-04-07 17:02 UTC, armenr commented
I was about to add the same thing today, @xavidop - 

The templates are dangerous without the explicit `.Release.Namespace`

Have a look at mine. Thank you BOTH for YOUR hard work!

https://github.com/armenr/helm-k8s-ecr-login-renew

2022-05-02 20:17 UTC, PawelLipski commented on chart/templates/cron.yaml
> +  schedule: "* */6 * * *"
One thing! I'd suggest adding a `pre-install` Helm hook (a Pod)... b/c otherwise now the credentails won't be filled up until the first run of the cron job :/

2022-05-02 22:17 UTC, devec0 commented on chart/templates/cron.yaml
> +                    key: DOCKER_SECRET_NAME
Ah, yep, I hit the same issue and ended up adding this to my local copy. I'll push those changes.

2022-05-02 22:18 UTC, devec0 commented on chart/templates/cron.yaml
> +  schedule: "* */6 * * *"
Thanks, this is a good idea. I'll push this change in a sec.

2022-05-02 22:28 UTC, devec0 commented
I've pushed some updates including -

* Passing the deployment namespace to the job by default
* Allowing override of the namespace from helm configuration explicitly
* Adding a pre-install hook that creates the job for immediate renewal on install

Thanks @PawelLipski and @xavidop for the helpful review and kind words.

2022-05-02 22:29 UTC, devec0 commented
Additionally, if anyone has changes they would like to make, and would like push access to the forked version I have attached to this PR, either open a PR on my repo and I'll merge and push it - or just please let me know, I will grant push access if needed.

2022-05-02 23:15 UTC, nabsul commented
I did start learning Helm yesterday finally :-). Hopefully in the next week or two I'll be in a position to review and merge this.

2022-05-02 23:17 UTC, devec0 commented
Please take your time @nabsul - helm takes some time to get used to, but it is worth it, and thanks for considering this PR 🙂

2022-05-03 08:03 UTC, PawelLipski commented on chart/templates/cron.yaml
> +                    name: {{ include "k8s-ecr-login-renew.secret" . }}
Hmmm I don't think it makes sense to read namespace name from a secret 🤔 as in, it's much better retrieved from Helm values directly

2022-05-03 08:04 UTC, PawelLipski commented on chart/templates/cron.yaml
> +                    name: {{ include "k8s-ecr-login-renew.secret" . }}
Actually, in my similar chart, I'm using a single instance of renewer for multiple namespaces:

```
                - name: TARGET_NAMESPACE
                  # Despite a singular name of the env var itself,
                  # multiple namespaces can be provided - see https://github.com/nabsul/k8s-ecr-login-renew#multiple-namespace-support
                  value: {{ join "," .Values.targetNamespaces }}
```

2022-05-03 08:06 UTC, PawelLipski commented on chart/templates/cron.yaml
> +{{ include "k8s-ecr-login-renew.podLabels" . | indent 12 }}
Pls keep the `{{` actions indented more in line with the surrounding YAML... e.g. here I'd start the `{{` on the level one deeper than the `labels:` above

2022-05-03 08:07 UTC, PawelLipski commented on chart/templates/cron.yaml
> +{{- if .Values.overrideNamespace }}
Similarly for the `if`s, pls indent for better readability

2022-05-03 08:09 UTC, PawelLipski commented on chart/templates/cron.yaml
> +                    name: {{ include "k8s-ecr-login-renew.secret" . }}
Yeah... I don't think any of these values, other than `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` needs to be provided via `secretKeyRef`. For the reference, here's how it looks like in my chart currently:

```yaml
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-ecr-credentials
              key: accessKeyId
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-ecr-credentials
              key: secretAccessKey
        - name: DOCKER_REGISTRIES
          value: "{{ .Values.ecrRegistry }}"
        - name: DOCKER_SECRET_NAME
          value: ecr-docker-credentials
        - name: TARGET_NAMESPACE
          value: "{{ join "," .Values.targetNamespaces }}"
```

2022-05-03 08:11 UTC, PawelLipski commented on chart/templates/serviceaccount.yaml
> +  - kind: ServiceAccount
Hmmm what about the target namespace here? 🤔 

Compare:

```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install
    # We use a smaller weight than for ecr-docker-credentials-renewer pod so that the resources are created before the pod.
    "helm.sh/hook-weight": "10"
    # We can't delete the service account (and other resources defined in this file)
    # after running the hook since it's needed for the CronJob as well.
    "helm.sh/hook-delete-policy": before-hook-creation


{{- range .Values.targetNamespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, update, get, delete]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-docker-credentials-renewer
subjects:
  - kind: ServiceAccount
    name: ecr-docker-credentials-renewer
    namespace: "{{ $.Release.Namespace }}"
{{- end }}
```

2022-05-03 08:11 UTC, PawelLipski commented on chart/templates/serviceaccount.yaml
> +  name: {{ include "k8s-ecr-login-renew.roleBinding" . }}
Hmmm what about the target namespace here? 🤔 

Compare:

```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install
    # We use a smaller weight than for ecr-docker-credentials-renewer pod so that the resources are created before the pod.
    "helm.sh/hook-weight": "10"
    # We can't delete the service account (and other resources defined in this file)
    # after running the hook since it's needed for the CronJob as well.
    "helm.sh/hook-delete-policy": before-hook-creation


{{- range .Values.targetNamespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [create, update, get, delete]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-docker-credentials-renewer
  namespace: "{{ . }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-docker-credentials-renewer
subjects:
  - kind: ServiceAccount
    name: ecr-docker-credentials-renewer
    namespace: "{{ $.Release.Namespace }}"
{{- end }}
```

2022-05-05 07:29 UTC, armenr commented on chart/templates/cron.yaml
> +                    name: {{ include "k8s-ecr-login-renew.secret" . }}
This is a good idea. 👍🏼

2022-08-13 08:49 UTC, PawelLipski commented
Hey there... any updates here? ;)

2022-08-13 17:56 UTC, nabsul commented
My update from the last three months:

- [ ] Prepare for arrival of baby (never completely finished, but as much as possible)
- [ ] Prepare for parental leave by wrapping up / handing over work projects
- [ ] Baby arrives
- [ ] Get used to new life with baby
- [ ] Catch up on open source projects (this PR is the first priority)
- [ ] Go back to work (mid-september)

I make no promises, but I really do want to get this done, and I think I'll have the energy (and need the distraction from baby-work) as I adjust to baby life. 🤞 🤞 😄

2022-08-14 01:05 UTC, devec0 commented
> My update from the last three months:
> 
>     * [x]  Prepare for arrival of baby (never completely finished, but as much as possible)
> 
>     * [x]  Prepare for parental leave by wrapping up / handing over work projects
> 
>     * [x]  Baby arrives
> 
>     * [ ]  Get used to new life with baby
> 
>     * [ ]  Catch up on open source projects (this PR is the first priority)
> 
>     * [ ]  Go back to work (mid-september)
> 
> 
> I make no promises, but I really do want to get this done, and I think I'll have the energy (and need the distraction from baby-work) as I adjust to baby life. 🤞 🤞 😄

Congratulations @nabsul 🎉 🎊 
It looks to me like your priorities are correct 👍🏻

2022-08-14 17:17 UTC, PawelLipski commented
Wow congrats indeed! No rush, take a good care of the baby 👶🏻 
Girl or boy btw? ;)

2022-08-16 16:08 UTC, nabsul commented
Boy :-) And thank you all for all the kind words ❤️

So many decisions to make with this new child, like: Do I teach him Go or C# first? 😆

2022-08-18 09:16 UTC, Startouf requested changes
I suggest not creating the secret via values to preserve confidentiality. A note could be added to the readme explaining how to create the secret

```
# secrets.nocommit.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: xxx
type: Opaque
data:
  aws-acces-key-id: xxx=
  aws-secret-access-key: xxx=
  
# kubectl apply -f ./secrets.nocommit.yaml
```

What do you think ?

2022-08-18 09:16 UTC, Startouf commented on chart/templates/secret.yaml
> +{{- end }}
I have a very mitigated opinion regarding the generation of this secret via values and security, and this is why I don't like existing charts. 

If you create a secret via Helm values, this kills all confidentiality, as you will be able to access the secret by reading the released chart user-provided values (correct me if I'm wrong).

IMO, the creation of this secret should be left at the user's convenience, and NOT through helm value. Which is why I suggest to make the secret name and key configurable by the user
(or have the values of the generated secret be themselves secretKeyRef for AWS AK/SK), and just add a notice in the readme with a sample secret.yaml that the user needs to apply directly with kubectl apply

What do you think ?

2022-08-18 09:16 UTC, Startouf commented on chart/values.yaml
> +  secretAccessKey: ""
Regarding my previous question and confidentiality of the secret

```suggestion
  secretName: ""
  awsAccessKeyID_key: ""
  awsSecretAccessKey_key
```

2022-08-18 09:16 UTC, Startouf commented on chart/templates/cron.yaml
> +                    key: AWS_SECRET_ACCESS_KEY
See my previous comment

Is it possible to make the secret name + keys configurable via the values ? I like to reuse existing AWS credentials secrets across several apps like this and it's impossible if they each have a different name/key.

(don't forget to propagate to the pre-install-job as well)

```suggestion
                    name: {{ include "k8s-ecr-login-renew.secret" . }}
                    key: {{ .Values.ecr.AwsAccessKeyId_key }}
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ include "k8s-ecr-login-renew.secret" . }}
                    key: {{ .Values.ecr.AwsSecretAccessKey_key }}
```

2022-08-18 09:16 UTC, Startouf commented on chart/templates/definitions.tpl
> +{{- default (printf "%s-secret" .Release.Name) -}}
```suggestion
{{- .Values.ecr.secretName | default (printf "%s-secret" .Release.Name) -}}
```

2022-08-18 09:18 UTC, Startouf commented on chart/templates/definitions.tpl
> +{{- default (printf "%s-secret" .Release.Name) -}}
Actually if you want to follow my approach, we can completely remove this from the helper

2022-08-18 12:06 UTC, devec0 commented on chart/templates/secret.yaml
> +{{- end }}
For helm3, the values are stored as a secret in k8s, so it's not really an issue for storing the secrets in helm values.

I do agree it would be good to make the secret creation optional, as some people will use other tools (such as terraform) to precreate the secret. If you want to put together a PR for this against my fork, I'll merge it into this PR.

2022-08-18 13:16 UTC, Startouf commented on chart/templates/secret.yaml
> +{{- end }}
@devec0 been working on this, I'm not using windows so it would be better is someone else coud run tests https://github.com/devec0/k8s-ecr-login-renew/pull/1

2022-08-19 09:37 UTC, devec0 commented
> I suggest not creating the secret via values to preserve confidentiality. A note could be added to the readme explaining how to create the secret
> 
> ```
> # secrets.nocommit.yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: aws-secrets
>   namespace: xxx
> type: Opaque
> data:
>   aws-acces-key-id: xxx=
>   aws-secret-access-key: xxx=
>   
> # kubectl apply -f ./secrets.nocommit.yaml
> ```
> 
> What do you think ?

Thank you for your fantastic improvements and suggestions @Startouf - I've reviewed them and merged them into this PR.

2022-08-19 14:12 UTC, nabsul commented
> I suggest not creating the secret via values to preserve confidentiality. A note could be added to the readme explaining how to create the secret
> 
> ```
> # secrets.nocommit.yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: aws-secrets
>   namespace: xxx
> type: Opaque
> data:
>   aws-acces-key-id: xxx=
>   aws-secret-access-key: xxx=
>   
> # kubectl apply -f ./secrets.nocommit.yaml
> ```
> 
> What do you think ?

I agree with this by the way. The secret should be a prerequisite, not a configuration parameter.

2022-08-22 02:53 UTC, nabsul requested changes
This is a fantastic start! I didn't have a chance to fully review and test thing, but I have started reading the Helm docs, and based on what I've learned so far, I have a few suggestions.

I didn't have time today, but I'd be happy to make some of these changes myself. I think I can submit suggested changes as pull requests into your branch...

2022-08-22 02:53 UTC, nabsul commented on chart/values.yaml
> +  tag: latest
I think this should be hard-coded to a specific version. To be honest, I regret ever releasing a `latest` tag :-). I don't want anyone to take a dependency on that.

2022-08-22 02:53 UTC, nabsul commented on chart/values.yaml
> +  region: us-east-1
Probably best to force the user to enter a region explicitly?

2022-08-22 02:53 UTC, nabsul commented on index.yaml
> +    - https://nabsul.github.io/k8s-ecr-login-renew/k8s-ecr-login-renew-0.1.tgz
Instead of checking the package into the repo like this, how about we try to follow this recommendation: https://docs.helm.sh/docs/howto/chart_releaser_action/

2022-08-22 02:53 UTC, nabsul commented on chart/templates/definitions.tpl
> +{{- end }}
nit: add new line

2022-08-22 02:53 UTC, nabsul commented on README.md
> +### Deploy to Kubernetes with Helm 3
Probably best to add a note before this section that says something like "there are two ways to deploy this tool, and you only need to use one of these..."

2022-08-22 08:23 UTC, Startouf commented on .gitignore
> +*~
I think we can remove this

2022-08-22 08:25 UTC, Startouf commented on README.md
> +The tool is mainly configured through environment variables (and/or secrets in kubernetes). These are:
My bad, this is a leftover and can be removed/reverted

2022-08-22 08:30 UTC, Startouf commented on chart/values.yaml
> +  region: us-east-1
This is the default AWS region configured in most AWS APIs. 
There is little problem here leaving this default value, as using an ECR repository in a region that does not exist should trigger a meaningful error message from AWS.

But we can also leave it blank as you suggest, I have just not tested what error is given if this is left empty, I hope it's meaningful, and not just a "failed to parse nil as string" or something like this. I'm also the first to be annoyed that us-east-1 is the default region in some tools since I'm in Europe and sometimes end up creating resources in US regions I don't want because of this default.

2022-08-22 08:30 UTC, Startouf commented on index.yaml
> +    - https://nabsul.github.io/k8s-ecr-login-renew/k8s-ecr-login-renew-0.1.tgz
I was not aware of this documentation, this would be better indeed.

2022-08-22 08:31 UTC, Startouf commented
@devec0 can you handle nabsul's review requested changes ?

2022-08-23 10:10 UTC, devec0 commented on .gitignore
> +*~
It's for emacs backup files

2022-08-23 10:19 UTC, devec0 commented on chart/values.yaml
> +  region: us-east-1
We can use the `required` template filter here to gracefully handle this. The general pattern I've seen with helm charts is that it is better to have a default value but I agree with having this as a required value as while most people will have their registry in us-east-1, many won't.

2022-08-23 10:37 UTC, devec0 commented on README.md
> +### Deploy to Kubernetes with Helm 3
Agreed, I've clarified this in the README

2022-08-23 10:39 UTC, devec0 commented on chart/templates/definitions.tpl
> +{{- end }}
done

2022-08-23 10:40 UTC, devec0 commented on index.yaml
> +    - https://nabsul.github.io/k8s-ecr-login-renew/k8s-ecr-login-renew-0.1.tgz
I've added the workflow - I _think_ the required environment variables should already be set by GitHub

2022-08-23 10:40 UTC, devec0 commented on chart/values.yaml
> +  tag: latest
I've set the version to the latest tag, v1.7.1

2022-08-23 10:41 UTC, devec0 commented on .gitignore
>  .idea
I've made the .gitignore and .helmignore consistent and added comments explaining the entries

2022-08-23 10:41 UTC, devec0 commented on README.md
> +Once that's created, you'll want to get the Access Key ID and Secret access Key (AK/SK) of the user for the next step.
done

2022-08-23 10:41 UTC, devec0 commented on README.md
> +The tool is mainly configured through environment variables (and/or secrets in kubernetes). These are:
done

2022-08-23 10:43 UTC, devec0 commented
> > I suggest not creating the secret via values to preserve confidentiality. A note could be added to the readme explaining how to create the secret
> > ```
> > # secrets.nocommit.yaml
> > apiVersion: v1
> > kind: Secret
> > metadata:
> >   name: aws-secrets
> >   namespace: xxx
> > type: Opaque
> > data:
> >   aws-acces-key-id: xxx=
> >   aws-secret-access-key: xxx=
> >   
> > # kubectl apply -f ./secrets.nocommit.yaml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do you think ?
> 
> I agree with this by the way. The secret should be a prerequisite, not a configuration parameter.

Also, I wanted to add to this specifically - the values support is important when working with other tools and things like the helm-secrets plugin to do proper secrets management. I think having both is the right call if you want to be able to supply the secret as a pre-existing definition configured by some other tool (like terraform). Additionally, helm3 stores the values as secrets so there is no downside from a security perspective either.

2022-09-03 15:47 UTC, nabsul commented
Heyo! I'm going to take this into a local branch on this repo to make it easier to continue the work.

2022-09-03 15:48 UTC, nabsul commented
https://github.com/nabsul/k8s-ecr-login-renew/pull/38

2022-09-09 01:07 UTC, nabsul commented
Thanks again for your contributions here! I believe I have https://github.com/nabsul/k8s-ecr-login-renew/pull/38 working the I want it to work. This PR was a great base to start from, but I decided to deviate a bit in the following ways:

- Avoid pre-hooks and just have all resource created in the main event
- Skip the one-off job creation in favor of giving the user the one-liner kubectl command needed to run the cronjob once manually
- I tried Helm's recommended GH action for publishing the repo, but the more I understand how repos work, the more I feel like it's not a great solution. The main reasons being:
  - The Helm chart for this tool should live in the same repo as the actual tool/code
  - The repo index however can accommodate multiple tools/projects (I plan to add a Helm chart for KCert), so the `index.yaml` file should NOT live in this repo. I have moved it to [`https://github](https://nabsul.github.io/helm/index.yaml)
  - I don't believe in checking tgz files into the git repo. Right now I'm manually creating the tgz file and uploading it as a release. In a later step, I'll create a GH action that does this automatically.
  - Automating the `index.yaml` file would be nice, but for now I'll manually edit it whenever there's a new release.
- I still would like to provide a raw-yaml approach for people who prefer `kubectl apply`, but I'll have that code auto-generated from Helm's `--debug` and dry-run commands. This will eliminate the need to maintain two separate ways to install the tool.

2022-09-09 01:16 UTC, devec0 commented
@nabsul - I'll close this one out in favour of #38

2022-09-09 01:16 UTC, closed without merging