feat: add helm chart more re-suable
nabsul/k8s-ecr-login-renew pull request #41
Opened 2022-09-28 10:59 UTC by xavidop

I exposed more values that can be set in the helm chart so with that is more re-suable

2022-09-28 10:59 UTC, xavidop commented
@nabsul just tested on my clusters and its working fine. Let me know what you think!

2022-09-28 20:54 UTC, nabsul requested changes
This looks like a really nice thing to add overall. I just have a couple of small requests for consistency.

2022-09-28 20:54 UTC, nabsul commented on chart/values.yaml
> +# the schedule of the cronjob
Two suggestions: 

1) I would like to order values in this file according to how likely someone is going to need to edit it. So how about we move these further down? I think right after `registries` would be good.

2) Since these are all cronjob parameters, maybe put them all under a `cronJob` parent. Otherwise, as we add more and more possibilities to this file, we'll end up with a very long flat list of variables. (I tried to only put the most important variables at the top level).

2022-09-29 08:57 UTC, xavidop commented on chart/values.yaml
> +# the schedule of the cronjob
Hi Nansul I just addressed your changes! btw I found an issue with the crontab!!! We had set to `* */6 * * *` this means that will be At every minute past every 6th hour. what we want is to execute this just once every 6 hours -> `0 */6 * * *`

2022-09-29 08:57 UTC, xavidop commented on chart/values.yaml
> +# the schedule of the cronjob
@nabsul do you think that we can merge these changes today?

2022-09-29 23:57 UTC, nabsul commented on chart/values.yaml
> +# the schedule of the cronjob
Wow, good catch on the cron tab. I'll try to get this merged shortly.

2022-09-29 23:59 UTC, nabsul commented on chart/templates/005-CronJob.yaml
> +{{- if .Values.cronjob.startingDeadlineSeconds }}
Let's add this one to the values.yaml so that it's documented as existing.

2022-09-29 23:59 UTC, nabsul commented on chart/templates/005-CronJob.yaml
> +{{- if .Values.cronjob.startingDeadlineSeconds }}
I'll go ahead and merge and add this.

2022-09-29 23:59 UTC, nabsul approved these changes

2022-09-30 00:00 UTC, merged

2022-09-30 00:11 UTC, nabsul commented
Helm chart is published.

2022-09-30 00:19 UTC, xavidop commented
THANKS!!!